// wasm/web/engine-worker.js - Neovim engine endpoint, run in a Web Worker.
//
// The browser analogue of wasm/worker.js. Hosts the Neovim engine wasm
// (`nvim --embed`) directly in this Worker and backs its stdin/stdout (fd 0/1)
// with a postMessage channel to the page (wasm/nvim_io.js installs the stream
// ops). The page and the engine only ever exchange messages -- no shared memory,
// so the page needs no COOP/COEP / cross-origin isolation.
//
// Protocol with the page:
//   page -> worker:  first message {args, env, cwd, filesystem, plugins} (init);
//                    then ArrayBuffers (RPC input)
//   worker -> page:  ArrayBuffers (RPC output); {kind:'booting'|'stdout'|'stderr'
//                    |'exit'} status objects
//
// Runtime VARIANTS (the create({plugins}) option): nvim.wasm is runtime-agnostic,
// so the runtime ships as a separate file_packager data package per variant
// (nvim-<variant>.data + nvim-<variant>.data.js loader). The loader unpacks the
// runtime into MEMFS at /usr/share/nvim/runtime and, crucially, registers a
// run-dependency (addRunDependency / preRun) on `self.Module`, so nvim's main()
// waits for the data before it runs. We MUST importScripts the loader BEFORE
// nvim.js, and self.Module must already exist so the loader's
// `var Module = typeof Module != 'undefined' ? Module : {}` binds to OUR Module
// (the same one nvim.js then uses) rather than a throwaway object.
'use strict';

var VARIANTS = { full: 1, core: 1, minimal: 1 };
var started = false;

onmessage = function (e) {
  if (!started) {
    started = true;
    var init = e.data || {};
    var args = init.args || [];

    // The channel object wasm/nvim_io.js reads (Module.nvimChannel).
    var channel = {
      inQueue: [],
      closed: false,
      notify: null,
      postOutput: function (u8) { postMessage(u8.buffer, [u8.buffer]); },
    };
    self.__nvimChannel = channel;
    self.__nvimArgs = ['--embed'].concat(args);

    // create() runtime config (env/cwd/filesystem) travels in the same init
    // message and is handed to the engine via the __nvim* globals pre.js reads,
    // mirroring the Node host (wasm/worker.js) exactly.
    if (init.env) { self.__nvimEnv = init.env; }
    if (init.filesystem) { self.__nvimFiles = init.filesystem; }
    if (typeof init.cwd === 'string') { self.__nvimCwd = init.cwd; }

    // Surface engine stdout/stderr + exit back to the page. Set BEFORE boot so the
    // engine's own prints are captured even on the deferred-boot (proxy) path.
    self.Module = self.Module || {};
    self.Module.print = function (s) { try { postMessage({ kind: 'stdout', text: s }); } catch (_e) {} };
    self.Module.printErr = function (s) { try { postMessage({ kind: 'stderr', text: s }); } catch (_e) {} };
    self.Module.onExit = function () { try { postMessage({ kind: 'exit' }); } catch (_e) {} };

    // Runtime variant: default 'full'. create() already validates this, but guard
    // here too since the worker can be driven directly.
    var variant = init.plugins || 'full';

    // bootEngine loads the variant's data package + nvim.js (which runs main()).
    // Idempotent: the proxy path can race several boot signals (hello / failed
    // connect / backstop timer) and only the first one boots.
    var booted = false;
    function bootEngine() {
      if (booted) { return; }
      booted = true;
      if (!VARIANTS[variant]) {
        postMessage({ kind: 'error', error: "unknown plugins variant '" + variant +
          "' (expected 'full', 'core', or 'minimal')" });
        return;
      }
      postMessage({ kind: 'booting' });
      // Load the variant's data-package loader FIRST (it registers a run-dependency
      // on self.Module + a preRun that unpacks the runtime into MEMFS), THEN nvim.js
      // (which sees the dependency and waits for the data before main()). Both
      // resolve relative to this worker's URL, i.e. under the bundle's baseUrl.
      //
      // The data-package loader is generated by wasm/build-nvim.sh (file_packager).
      // If the build is stale (predates the runtime-variants change) the file is
      // absent and importScripts throws an opaque NetworkError -- catch it and post
      // an actionable message instead of letting the worker die silently.
      try {
        importScripts('nvim-' + variant + '.data.js');
      } catch (err) {
        postMessage({ kind: 'error', error:
          "failed to load the runtime package 'nvim-" + variant + ".data.js' (" +
          (err && err.message || err) + "). The wasm build is likely stale -- run " +
          "wasm/build-nvim.sh to (re)generate the per-variant runtime data packages " +
          "next to nvim.js." });
        return;
      }
      importScripts('nvim.js');   // boots the engine; main() runs the libuv loop
    }

    // Stage 4 (additive/opt-in): if the page passed a `proxy` config, open the
    // engine's OWN WebSocket to the IO-proxy server, wrap it as a transport, run
    // the shared proxy client over it, send the hello handshake, and stash the
    // client at globalThis.__nvimProxy so the js-libraries can find it. When
    // init.proxy is ABSENT we boot immediately -- no connection, current behavior.
    //
    // With a proxy we DEFER boot until the first hello settles, so the server's
    // reported identity (the proxied user -> $USER, read by pre.js) is in place
    // before the engine's main() runs. A boot signal fires on: (a) a successful
    // hello (we have the user); (b) a failed first connect (server down -> boot
    // degraded, no user); (c) a backstop timer (a socket that opens but never
    // acks). A connection failure must NOT crash the worker; bootEngine() is
    // idempotent so whichever fires first wins.
    if (init.proxy && init.proxy.url) {
      var bootBackstop = setTimeout(function () {
        try { postMessage({ kind: 'stderr', text: 'proxy: no hello within timeout; booting without server identity' }); } catch (_e) {}
        bootEngine();
      }, 8000);
      function bootSignal(helloResult) {
        if (helloResult && typeof helloResult.user === 'string' && helloResult.user) {
          self.__nvimProxyUser = helloResult.user;   // pre.js reads this for $USER
        }
        clearTimeout(bootBackstop);
        bootEngine();
      }
      try { setupProxy(init.proxy, bootSignal); }
      catch (err) {
        try { postMessage({ kind: 'stderr', text: 'proxy setup failed: ' + (err && err.message || err) }); } catch (_e) {}
        clearTimeout(bootBackstop);
        bootEngine();
      }
    } else {
      bootEngine();
    }
    return;
  }

  // After init, every message is RPC input bytes (a transferred ArrayBuffer).
  var ch = self.__nvimChannel;
  ch.inQueue.push({ buf: new Uint8Array(e.data), off: 0 });
  if (ch.notify) { ch.notify(); }
};

// Stage 4: open the IO-proxy WebSocket and wire the shared proxy client. The
// client lives in wasm/proxy-client.js, importScripted into this worker (it sets
// self.ProxyClient). build-site.sh / build-lib.sh copy it next to nvim.js so it
// resolves at the bundle root, exactly like nvim.js. Connection failures are
// surfaced as a stderr status (the engine keeps running; no IO depends on it in
// Phase 1).
// `bootSignal(helloResult)` (optional) lets the caller defer the engine boot
// until the proxy's identity is known: it is called with the hello ack's result
// on each successful (re)connect, and with no argument on the first disconnect
// (server unreachable) so the caller can boot degraded rather than wait forever.
function setupProxy(proxy, bootSignal) {
  bootSignal = bootSignal || function () {};
  importScripts('proxy-client.js');     // sets self.ProxyClient
  importScripts('proxy-reconnect.js');  // sets self.ProxyReconnect (stage 5)

  // Phase 2: the FS-proxy js-library reads the mount prefix here. Default it to
  // '/host' when a proxy is configured but no mount was given (documented).
  self.__nvimProxyMount = (typeof proxy.mount === 'string' && proxy.mount.length)
    ? proxy.mount : '/host';

  // Stage 5 (durable PTYs): the session id carried in the /proxy URL (?session=)
  // routes this tab's :terminal shells to the session-host daemon so they survive
  // a transport drop. The host app passes a STABLE per-project id (proxy.session,
  // persisted in localStorage) so a full reload reconnects to the same session and
  // can rehydrate its terminals. If none was provided (library use without a host,
  // or localStorage blocked) we mint an ephemeral per-load id: durable across
  // reconnects, but not across a reload.
  self.__nvimSession = (typeof proxy.session === 'string' && proxy.session)
    ? proxy.session
    : ((self.crypto && self.crypto.randomUUID)
        ? self.crypto.randomUUID()
        : ('s-' + Date.now().toString(36) + '-' + Math.random().toString(36).slice(2)));

  // Stage 5: a RECONNECTING facade (wasm/proxy-reconnect.js) — a stable object the
  // js-libraries find at self.__nvimProxy. It delegates `request` to the current
  // live client (fast-rejecting during an outage so suspended syscalls return
  // -EIO instead of hanging), preserves the push router across reconnects, and
  // re-dials with backoff after a drop. The engine itself never restarts — only
  // the wire reconnects, so buffers/undo survive a blip (see stage5.md §6).
  self.__nvimProxy = self.ProxyReconnect.createReconnectingProxy({
    ProxyClient: self.ProxyClient,
    dial: function () {
      var url = proxy.url + (proxy.url.indexOf('?') >= 0 ? '&' : '?') +
        'session=' + encodeURIComponent(self.__nvimSession);
      var ws = new WebSocket(url);
      ws.binaryType = 'arraybuffer';
      return ws;
    },
    // nvimSocket goes in the hello so the SERVER knows nvim's RPC socket path and
    // can export $NVIM to spawned children (app.js serverstart()s on this path).
    helloParams: { mount: self.__nvimProxyMount, root: proxy.root, nvimSocket: proxy.nvimSocket },
    // Carries the hello ack's result (incl. the proxied `user` -> $USER) to the
    // deferred-boot logic above on every successful (re)connect.
    onHello: function (result) { try { bootSignal(result); } catch (_e) {} },
    onStatus: function (ev) {
      try {
        if (ev.kind === 'connected') {
          postMessage({ kind: 'stdout', text: 'proxy: connected to ' + proxy.url });
        } else if (ev.kind === 'disconnected') {
          // First disconnect with no prior hello == server unreachable: release the
          // deferred boot so the editor still loads (degraded), rather than hang.
          bootSignal();
          postMessage({ kind: 'stderr', text: 'proxy: connection lost — in-flight IO failed; reconnecting…' });
        } else if (ev.kind === 'reconnecting') {
          postMessage({ kind: 'stderr', text: 'proxy: reconnecting in ' + ev.delay + 'ms' });
        }
      } catch (_e) {}
    },
  });
}
